apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smokeping
resources:
  - namesapce.yaml
  - deployment/*
  - storage/*
  - services/*
  configMapGenerator:
- name: smokeping-config
  files:
  - CustomTargets.txt

