apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smokeping-ingress
  namespace: smokeping
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smokeping 
            port:
              number: 80
