apiVersion: v1
kind: PersistentVolume
metadata:
  name: smokeping-pv-config
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-config-storage
  local:
    path: /media/pistore/smokeping-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - piagent1
